es_host: elasticsearch
es_port: 9200

writeback_index: elastalert_status

buffer_time:
  minutes: 1
run_every:
  minutes: 1

rules_folder: /opt/elastalert/rules
alert_time_limit:
  days: 2

#SMTP configuration
smtp_host: "smtp.gmail.com"
smtp_port: 465
smtp_ssl: true
from_addr: "sender@gmail.com"
smtp_auth_file: '/opt/elastalert/smtp_auth.yaml'